const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'lib', 'pdfGenerator.ts');

// Helper: build the full content to append
const lines = [];
function L(s) { lines.push(s); }

// ── palette & helpers (module-level but outside export) ──────────────────────
L('');
L('// ─── Report PDF helpers ────────────────────────────────────────────────────');
L('');
L('function _rfmt(n: number): string {');
L('  if (isNaN(n) || n === null || n === undefined) return "Tsh 0";');
L('  return new Intl.NumberFormat("en-TZ", {');
L('    style: "currency", currency: "TZS",');
L('    minimumFractionDigits: 0,');
L('    notation: Math.abs(n) >= 1_000_000 ? "compact" : "standard",');
L('    compactDisplay: "short"');
L('  }).format(n);');
L('}');
L('');
L('function _bname(loan: any): string {');
L('  const b = loan?.borrower;');
L('  if (!b) return "Unknown";');
L('  return ((b.firstName || "") + " " + (b.lastName || "")).trim() || "Unknown";');
L('}');
L('');
L('function _hdr(');
L('  doc: any,');
L('  title: string,');
L('  period: string,');
L('  pageNum: number,');
L('  totalPages: number,');
L('  RP: [number,number,number],');
L('  RW: [number,number,number],');
L('  RL: [number,number,number],');
L('  RS: [number,number,number]');
L(') {');
L('  const W = doc.internal.pageSize.getWidth();');
L('  doc.setFillColor(...RP);');
L('  doc.rect(0, 0, W, 18, "F");');
L('  doc.setTextColor(...RW);');
L('  doc.setFontSize(11);');
L('  doc.setFont("helvetica", "bold");');
L('  doc.text("AFAR MKOPO FASTA", 14, 11);');
L('  doc.setFontSize(8);');
L('  doc.setFont("helvetica", "normal");');
L('  doc.text(title, W / 2, 11, { align: "center" });');
L('  doc.text(`Page ${pageNum} / ${totalPages}`, W - 14, 11, { align: "right" });');
L('  doc.setFillColor(...RL);');
L('  doc.rect(0, 18, W, 6, "F");');
L('  doc.setTextColor(...RS);');
L('  doc.setFontSize(7);');
L('  doc.text(period, 14, 22);');
L('  doc.text("Annual Company Report", W - 14, 22, { align: "right" });');
L('  doc.setTextColor(0, 0, 0);');
L('}');
L('');
L('function _ftr(');
L('  doc: any,');
L('  generatedAt: string,');
L('  RS: [number,number,number],');
L('  RL: [number,number,number]');
L(') {');
L('  const W = doc.internal.pageSize.getWidth();');
L('  const H = doc.internal.pageSize.getHeight();');
L('  doc.setFillColor(...RL);');
L('  doc.rect(0, H - 10, W, 10, "F");');
L('  doc.setTextColor(...RS);');
L('  doc.setFontSize(7);');
L('  doc.text("AFAR MKOPO FASTA — CONFIDENTIAL", 14, H - 3.5);');
L('  doc.text(`Generated: ${generatedAt}`, W - 14, H - 3.5, { align: "right" });');
L('  doc.setTextColor(0, 0, 0);');
L('}');
L('');
L('function _banner(');
L('  doc: any,');
L('  text: string,');
L('  y: number,');
L('  RP: [number,number,number],');
L('  RW: [number,number,number]');
L('): number {');
L('  const W = doc.internal.pageSize.getWidth();');
L('  doc.setFillColor(...RP);');
L('  doc.rect(14, y, W - 28, 7, "F");');
L('  doc.setTextColor(...RW);');
L('  doc.setFontSize(9);');
L('  doc.setFont("helvetica", "bold");');
L('  doc.text(text, 17, y + 5);');
L('  doc.setTextColor(0, 0, 0);');
L('  doc.setFont("helvetica", "normal");');
L('  return y + 10;');
L('}');
L('');
L('function _sub(');
L('  doc: any,');
L('  text: string,');
L('  y: number,');
L('  RD: [number,number,number]');
L('): number {');
L('  doc.setTextColor(...RD);');
L('  doc.setFontSize(9);');
L('  doc.setFont("helvetica", "bold");');
L('  doc.text(text, 14, y);');
L('  doc.setLine && doc.setLineWidth(0.3);');
L('  doc.setDrawColor(200, 200, 200);');
L('  const W = doc.internal.pageSize.getWidth();');
L('  doc.line(14, y + 1.5, W - 14, y + 1.5);');
L('  doc.setTextColor(0, 0, 0);');
L('  doc.setFont("helvetica", "normal");');
L('  return y + 6;');
L('}');
L('');
L('function _kpi(');
L('  doc: any,');
L('  x: number, y: number, w: number, h: number,');
L('  label: string, value: string, sub: string,');
L('  color: [number,number,number],');
L('  RW: [number,number,number],');
L('  RL: [number,number,number]');
L(') {');
L('  doc.setFillColor(...RL);');
L('  doc.roundedRect(x, y, w, h, 2, 2, "F");');
L('  doc.setFillColor(...color);');
L('  doc.rect(x, y, 2.5, h, "F");');
L('  doc.setTextColor(...color);');
L('  doc.setFontSize(7);');
L('  doc.setFont("helvetica", "bold");');
L('  doc.text(label.toUpperCase(), x + 5, y + 5);');
L('  doc.setTextColor(30, 41, 59);');
L('  doc.setFontSize(11);');
L('  doc.text(value, x + 5, y + 12);');
L('  doc.setTextColor(100, 116, 139);');
L('  doc.setFontSize(7);');
L('  doc.setFont("helvetica", "normal");');
L('  doc.text(sub, x + 5, y + 17);');
L('  doc.setTextColor(0, 0, 0);');
L('}');
L('');

fs.writeFileSync(filePath + '.helper.tmp', lines.join('\n'), 'utf8');
console.log('helpers written');
